name: Export DITAP SCORM Packages

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  release:
    types: [ published ]

jobs:
  export-scorm:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        module:
          - path: "3_Curriculum/3A_DITAP-Core-Curriculum/Module-0/Self-Paced Materials/1_Program Pre-Assessment.md"
            package: "Module0_Pre-Assessment"
          - path: "3_Curriculum/3A_DITAP-Core-Curriculum/Module-0/Self-Paced Materials/2_Orientation.md"
            package: "Module0_Orientation"
          - path: "3_Curriculum/3A_DITAP-Core-Curriculum/Module-1/Sprint-1/Self-Paced Materials/1_The Digital Services Landscape.md"
            package: "Module1_Sprint1"
          - path: "3_Curriculum/3A_DITAP-Core-Curriculum/Module-1/Sprint-2/Self-Paced Materials/1_Digital Service Methods, Roles, and Sources of Supply.md"
            package: "Module1_Sprint2"
          - path: "3_Curriculum/3A_DITAP-Core-Curriculum/Module-1/Sprint-3/Self-Paced Materials/1_Digital Service Tech Bootcamp.md"
            package: "Module1_Sprint3"
          - path: "3_Curriculum/3A_DITAP-Core-Curriculum/Module-2/Sprint-1/Self-Paced Materials/1_Assessing Agency Readiness.md"
            package: "Module2_Sprint1"
          - path: "3_Curriculum/3A_DITAP-Core-Curriculum/Module-2/Sprint-2/Self-Paced Materials/1_Stakeholder and Customer Mapping.md"
            package: "Module2_Sprint2"
          - path: "3_Curriculum/3A_DITAP-Core-Curriculum/Module-2/Sprint-3/Self-Paced Materials/1_Defining Success for your Digital Services Acquisition.md"
            package: "Module2_Sprint3"
          - path: "3_Curriculum/3A_DITAP-Core-Curriculum/Module-2/Sprint-4/Self-Paced Materials/1_Conducting Effective Market Research.md"
            package: "Module2_Sprint4"
          - path: "3_Curriculum/3A_DITAP-Core-Curriculum/Module-3/Sprint-1/Self-Paced Materials/1_Developing a Successful Acquisition Strategy.md"
            package: "Module3_Sprint1"
          - path: "3_Curriculum/3A_DITAP-Core-Curriculum/Module-3/Sprint-2/Self-Paced Materials/1_Developing the Solicitation.md"
            package: "Module3_Sprint2"
          - path: "3_Curriculum/3A_DITAP-Core-Curriculum/Module-3/Sprint-3/Self-Paced Materials/1_Running a Successful Evaluation.md"
            package: "Module3_Sprint3"
          - path: "3_Curriculum/3A_DITAP-Core-Curriculum/Module-4/Sprint-1/Self-Paced Materials/1_Management of Digital Service Delivery.md"
            package: "Module4_Sprint1"
          - path: "3_Curriculum/3A_DITAP-Core-Curriculum/Module-4/Sprint-2/Self-paced/1_Performance Measurement Under Agile Delivery Contracts.md"
            package: "Module4_Sprint2"
          - path: "3_Curriculum/3A_DITAP-Core-Curriculum/Module-4/Sprint-3/Self-Paced Materials/1_Contract Kickoff.md"
            package: "Module4_Sprint3"
          - path: "3_Curriculum/3A_DITAP-Core-Curriculum/Module-4/Sprint-4/Self-paced/1_Contract Management and Problem Resolution.md"
            package: "Module4_Sprint4"
          - path: "3_Curriculum/3A_DITAP-Core-Curriculum/Module-5/Sprint-1/Self-paced/1_Leading Change as an Individual.md"
            package: "Module5_Sprint1"
          - path: "3_Curriculum/3A_DITAP-Core-Curriculum/Module-5/Sprint-2/Self-Paced Materials/1_Leading Organizational Change.md"
            package: "Module5_Sprint2"
          - path: "3_Curriculum/3A_DITAP-Core-Curriculum/Module-5/Sprint-2/Self-Paced Materials/2_Post-Program Assessment.md"
            package: "Module5_Sprint2_Post-Assessment"
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Generate artifact name
      id: artifact-name
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "name=PR${{ github.event.number }}-${{ matrix.module.package }}" >> $GITHUB_OUTPUT
        elif [ "${{ github.event_name }}" = "release" ]; then
          echo "name=${{ github.event.release.tag_name }}-${{ matrix.module.package }}" >> $GITHUB_OUTPUT
        else
          echo "name=${{ github.ref_name }}-${{ github.sha }}-${{ matrix.module.package }}" >> $GITHUB_OUTPUT
        fi
    
    - name: Export ${{ matrix.module.package }} to SCORM 1.2
      id: export
      uses: grugnog/LiaScript-Exporter@github-actions
      with:
        input-file: "${{ matrix.module.path }}"
        format: scorm1.2
        output-name: "${{ matrix.module.package }}"
        scorm-organization: "USDS Digital IT Acquisition Professional Training Program (DITAP)"
    
    - name: Upload SCORM package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.artifact-name.outputs.name }}
        path: ${{ steps.export.outputs.output-file }}
        retention-days: ${{ github.event_name == 'release' && 90 || 30 }}

  # Create a summary for releases
  create-release-summary:
    if: github.event_name == 'release'
    needs: export-scorm
    runs-on: ubuntu-latest
    
    steps:
    - name: Create release summary
      run: |
        cat >> $GITHUB_STEP_SUMMARY << 'EOF'
        # DITAP SCORM Packages - Release ${{ github.event.release.tag_name }}
        
        ## SCORM file structure
        
        Each module has separate SCORM 1.2 .zip packages for each sprint within that module. Each .zip is a self-contained SCORM package ready for LMS import.
        
        This design makes it easy for vendors to:
        
        * Download only the sprint they need without re-downloading the entire course.
        * Replace a single SCORM file in their LMS if updates are released (instead of re-importing all files).
        * Keep their LMS organized by mapping each sprint to a lesson, topic, or module.
        
        This approach reduces vendor workload and ensures smoother updates when future revisions are made.
        
        The following SCORM 1.2 packages have been generated and are available as artifacts:
        
        ## Module 0 - Foundation
        - Module0_Pre-Assessment.zip
        - Module0_Orientation.zip
        
        ## Module 1 - Digital Services Landscape  
        - Module1_Sprint1.zip (Digital Services Landscape)
        - Module1_Sprint2.zip (Methods, Roles, and Sources)
        - Module1_Sprint3.zip (Tech Bootcamp)
        
        ## Module 2 - Preparation
        - Module2_Sprint1.zip (Agency Readiness)
        - Module2_Sprint2.zip (Stakeholder Mapping)
        - Module2_Sprint3.zip (Defining Success)
        - Module2_Sprint4.zip (Market Research)
        
        ## Module 3 - Acquisition Strategy
        - Module3_Sprint1.zip (Acquisition Strategy)
        - Module3_Sprint2.zip (Solicitation Development)
        - Module3_Sprint3.zip (Evaluation)
        
        ## Module 4 - Contract Management
        - Module4_Sprint1.zip (Service Delivery Management)
        - Module4_Sprint2.zip (Performance Measurement)
        - Module4_Sprint3.zip (Contract Kickoff)
        - Module4_Sprint4.zip (Contract Management)
        
        ## Module 5 - Leadership & Change
        - Module5_Sprint1.zip (Individual Leadership)
        - Module5_Sprint2.zip (Organizational Change)
        - Module5_Sprint2_Post-Assessment.zip (Final Assessment)
        
        **Total: 19 SCORM packages**
        
        All packages were exported using the [LiaScript SCORM exporter](https://liascript.github.io/exporter/).
        
        ---
        
        ## Import Instructions
        
        1. Download the files you need.
        2. Do not unzip the .zip file. Import the .zip directly into your LMS.
        3. In your LMS, go to Course Import > SCORM Upload (terminology may vary).
        4. Import each module separately and arrange them in the correct order.
        5. Confirm SCORM settings in your LMS:
           * SCORM version: *[1.2]*
           * Completion: *[e.g., Passed/Completed, Viewed All Slides]*
           * Tracking: *[quiz score, progress, or completion – specify]*
        
        ---
        
        ## Notes for LMS Administrators
        
        * These are 19 separate SCORM packages; your LMS may treat each one as a lesson/topic.
        * If your LMS supports multi-SCORM packaging, you may be able to group them into one "master course."
        * File sizes vary; ensure your LMS supports uploads of at least ~125 MB.
        * For large downloads, use a stable connection to avoid corruption.
        
        ---
        
        ## Versioning
        
        * Current release: ${{ github.event.release.created_at }}
        * Vendors should replace older SCORM packages with the updated .zip files if available.
        * Vendors can also generate their own SCORM packages using the [LiaScript exporter](https://liascript.github.io/exporter/).
        
        ---
        
        ## Troubleshooting
        
        * If an import fails:
          * Verify you are importing the .zip (not the extracted folder).
          * Confirm your LMS supports the specified SCORM version.
          * Check LMS file size limits.
        * Contact your LMS Technical Support for further assistance.
        
        ---
        
        **Organization:** USDS Digital IT Acquisition Professional Training Program (DITAP)  
        **Format:** SCORM 1.2  
        **Generated:** ${{ github.event.release.created_at }}
        EOF
